### ISSUE TITLE
Handle banned users

### ISSUE THREAD

**Issue by 5har0varik** [5har0varik/steampy#9]
Handle 403 in case of inventory request:
Error during GET request or invalid JSON content: 403 Client Error: Forbidden for url: https://steamcommunity.com/inventory/76561199072654974/440/2?l=english&count=3000         

Traceback (most recent call last):
 
  File "/home/.local/lib/python3.10/site-packages/steampy-1.1.2-py3.10.egg/steampy/utils.py", line 190, in func_wrapper
    return func(self, *args, **kwargs)
  File "/home/.local/lib/python3.10/site-packages/steampy-1.1.2-py3.10.egg/steampy/client.py", line 175, in get_partner_inventory
    raise ApiException('Success value should be 1.')
steampy.exceptions.ApiException: Success value should be 1.

**Comment by 5har0varik** [comment]
fixed in proxy branch
